Feature/joseph
Timonwa/Open-Source-Practice-Repo pull request #7
Opened 2024-02-02 08:51 UTC by jokutten

I added my name to contributors list
 **Description**
please add my name to the contributors list

2024-02-02 08:55 UTC, jokutten commented
Respected sir/ madam
I had been struggling a lot with contribution but you have helped me to
learn something . It has boosted my confidence. Thanks a lot for helping me
out . I will look forward to really contribute to you and  maybe work with
your team in future .

On Fri, 2 Feb, 2024, 2:21 pm codesandbox[bot], ***@***.***>
wrote:

> Review or Edit in CodeSandbox
>
> Open the branch in Web Editor
> <https://codesandbox.io/p/github/jokutten/Open-Source-Practice-Repo/feature/joseph?mode=review&utm_source=gh_app>
> • VS Code
> <https://codesandbox.io/p/vscode?owner=jokutten&repo=Open-Source-Practice-Repo&branch=feature/joseph&utm_source=gh_app>
> • Insiders
> <https://codesandbox.io/p/vscode?owner=jokutten&repo=Open-Source-Practice-Repo&branch=feature/joseph&insiders=true&utm_source=gh_app>
>
> Open Preview
> <https://codesandbox.io/p/devtool/preview/jokutten/Open-Source-Practice-Repo/feature/joseph?task=preview&port=51423&redirect=true&utm_source=gh_app>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Timonwa/Open-Source-Practice-Repo/pull/7#issuecomment-1923349430>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAZFLG3WUFLXJBLR3L6EMRLYRSSI7AVCNFSM6AAAAABCWJXOU6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMRTGM2DSNBTGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-02 12:15 UTC, Timonwa commented
Hi @jokutten. Thank you for your kind words! I'm glad to hear that you found the contribution experience positive. I will review your PR now.

2024-02-02 12:18 UTC, Timonwa requested changes

2024-02-02 12:18 UTC, Timonwa commented on contributors/names.md
> +- [jobin sabu]
Could you please follow the format mentioned in the README to add your name? If you don't have a URL to link your name, just leave it blank, like so: [Your Name](). Once you've made the changes, I'll be happy to merge your request.

2024-02-02 14:46 UTC, jokutten commented
Respected Mam
I updated it. Please tell if I am mistaken . Sorry for the trouble. And
thanks for your support. Your work is helping so many students . Thanks for
your support to us

On Fri, 2 Feb, 2024, 5:49 pm Eyitimonwa Akintokun, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In contributors/names.md
> <https://github.com/Timonwa/Open-Source-Practice-Repo/pull/7#discussion_r1475989897>
> :
>
> > @@ -20,6 +20,7 @@
>
>  - [Jane Doe](https://example.com)
>  - [John Doe](https://example.com)
> +- [jobin sabu]
>
> Could you please follow the format mentioned in the README to add your
> name? If you don't have a URL to link your name, just leave it blank, like
> so: Your Name. Once you've made the changes, I'll be happy to merge your
> request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Timonwa/Open-Source-Practice-Repo/pull/7#pullrequestreview-1859116487>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAZFLG5DFH667Z57WF6PZMDYRTKTZAVCNFSM6AAAAABCWJXOU6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNJZGEYTMNBYG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-02 17:22 UTC, merged

2024-02-02 17:23 UTC, Timonwa commented
i have merged your PR. nice one, @JOBIN-SABU.

2024-02-03 01:41 UTC, JOBIN-SABU commented
Thanks a lot. Mam

On Fri, 2 Feb, 2024, 10:53 pm Eyitimonwa Akintokun, <
***@***.***> wrote:

> i have merged your PR. nice one, @JOBIN-SABU
> <https://github.com/JOBIN-SABU>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Timonwa/Open-Source-Practice-Repo/pull/7#issuecomment-1924341332>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAZFLG3FHWAQLPTXZVYGSX3YRUOITAVCNFSM6AAAAABCWJXOU6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMRUGM2DCMZTGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>